Transform: AWS::Serverless-2016-10-31

Parameters:
  QldbLedgerName:
    Type: String

Resources:
  Qldb:
    Type: AWS::QLDB::Ledger
    Properties: 
      Name: !Ref QldbLedgerName
      DeletionProtection: true
      PermissionsMode: ALLOW_ALL