Parameters:
  AppName:
    Type: String
  Environment:
    Type: String
  DomainName:
    Type: String
  HostedZoneId:
    Type: String
  CertificateArn:
    Type: String
  UiDomainName:
    Type: String
  ArtistPortalDomainName:
    Type: String
  # GoogleAppId:
  #   Type: String
  # GoogleAppSecret:
  #   Type: String
  # FacebookAppId:
  #   Type: String
  # FacebookAppSecret:
  #   Type: String

Resources:
  Cognito:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: cloudformation-cognito.yaml
      Parameters:
        AppName: !Ref AppName
        Environment: !Ref Environment
        UiDomainName: !Ref UiDomainName 
        GoogleAppId: !Ref GoogleAppId 
        GoogleAppSecret: !Ref GoogleAppSecret 
        FacebookAppId: !Ref FacebookAppId 
        FacebookAppSecret: !Ref FacebookAppSecret 

  Api:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: cloudformation-api.yaml
      Parameters:
        AppName: !Ref AppName
        Environment: !Ref Environment
        DomainName: !Ref DomainName
        HostedZoneId: !Ref HostedZoneId
        CertificateArn: !Ref CertificateArn
        UiDomainName: !Ref UiDomainName
        IdpClientId: !GetAtt Cognito.Outputs.IdpClientId
        IdpBasePath: !GetAtt Cognito.Outputs.IdpBasePath
        JwksUrl: !GetAtt Cognito.Outputs.JkwsUrl
        QldbLedgerName: !Sub '${AppName}-db'

  Qldb:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: cloudformation-qldb.yaml
      Parameters:
        AppName: !Ref AppName
