Transform: AWS::Serverless-2016-10-31

Parameters:
  AppName:
    Type: String

Resources:
  Qldb:
    Type: AWS::QLDB::Ledger
    Properties: 
      Name: !Sub '${AppName}-db'
      DeletionProtection: true
      PermissionsMode: ALLOW_ALL